server:
  port: 8761
spring:
  application:
    name:  eureka-server
  devtools:
    livereload:
      port: 9761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false #关闭自我保护机制，client下线后无心跳，不再显示





